name: flutter_leaflet
description: A Flutter component for leaflet integration.
version: 0.0.1
homepage: https://github.com/ginocampra/flutter_leaflet
repository: https://github.com/ginocampra/flutter_leaflet
issue_tracker: https://github.com/ginocampra/flutter_leaflet/issues

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  webview_flutter_web: ^0.2.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
